//Copyright 2013 Vastech SA (PTY) LTD
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

package common

// note: the reason why this is manual rather than say using the stringer tool is because the stringer tool will return ALLCAPS, which while correct an action for the program, will not yield correct attributes per GraphViz

var attributeString map[Attribute]string = map[Attribute]string{
	DAMPING:            "Damping",
	K:                  "K",
	URL:                "URL",
	_BACKGROUND:        "_background",
	AREA:               "area",
	ARROWHEAD:          "arrowhead",
	ARROWSIZE:          "arrowsize",
	ARROWTAIL:          "arrowtail",
	BB:                 "bb",
	BGCOLOR:            "bgcolor",
	CENTER:             "center",
	CHARSET:            "charset",
	CLUSTERRANK:        "clusterrank",
	COLOR:              "color",
	COLORSCHEME:        "colorscheme",
	COMMENT:            "comment",
	COMPOUND:           "compound",
	CONCENTRATE:        "concentrate",
	CONSTRAINT:         "constraint",
	DECORATE:           "decorate",
	DEFAULTDIST:        "defaultdist",
	DIM:                "dim",
	DIMEN:              "dimen",
	DIR:                "dir",
	DIREDGECONSTRAINTS: "diredgeconstraints",
	DISTORTION:         "distortion",
	DPI:                "dpi",
	EDGEURL:            "edgeURL",
	EDGEHREF:           "edgehref",
	EDGETARGET:         "edgetarget",
	EDGETOOLTIP:        "edgetooltip",
	EPSILON:            "epsilon",
	ESEP:               "esep",
	FILLCOLOR:          "fillcolor",
	FIXEDSIZE:          "fixedsize",
	FONTCOLOR:          "fontcolor",
	FONTNAME:           "fontname",
	FONTNAMES:          "fontnames",
	FONTPATH:           "fontpath",
	FONTSIZE:           "fontsize",
	FORCELABELS:        "forcelabels",
	GRADIENTANGLE:      "gradientangle",
	GROUP:              "group",
	HEADURL:            "headURL",
	HEAD_LP:            "head_lp",
	HEADCLIP:           "headclip",
	HEADHREF:           "headhref",
	HEADLABEL:          "headlabel",
	HEADPORT:           "headport",
	HEADTARGET:         "headtarget",
	HEADTOOLTIP:        "headtooltip",
	HEIGHT:             "height",
	HREF:               "href",
	ID:                 "id",
	IMAGE:              "image",
	IMAGEPATH:          "imagepath",
	IMAGESCALE:         "imagescale",
	INPUTSCALE:         "inputscale",
	LABEL:              "label",
	LABELURL:           "labelURL",
	LABEL_SCHEME:       "label_scheme",
	LABELANGLE:         "labelangle",
	LABELDISTANCE:      "labeldistance",
	LABELFLOAT:         "labelfloat",
	LABELFONTCOLOR:     "labelfontcolor",
	LABELFONTNAME:      "labelfontname",
	LABELFONTSIZE:      "labelfontsize",
	LABELHREF:          "labelhref",
	LABELJUST:          "labeljust",
	LABELLOC:           "labelloc",
	LABELTARGET:        "labeltarget",
	LABELTOOLTIP:       "labeltooltip",
	LANDSCAPE:          "landscape",
	LAYER:              "layer",
	LAYERLISTSEP:       "layerlistsep",
	LAYERS:             "layers",
	LAYERSELECT:        "layerselect",
	LAYERSEP:           "layersep",
	LAYOUT:             "layout",
	LEN:                "len",
	LEVELS:             "levels",
	LEVELSGAP:          "levelsgap",
	LHEAD:              "lhead",
	LHEIGHT:            "lheight",
	LP:                 "lp",
	LTAIL:              "ltail",
	LWIDTH:             "lwidth",
	MARGIN:             "margin",
	MAXITER:            "maxiter",
	MCLIMIT:            "mclimit",
	MINDIST:            "mindist",
	MINLEN:             "minlen",
	MODE:               "mode",
	MODEL:              "model",
	MOSEK:              "mosek",
	NODESEP:            "nodesep",
	NOJUSTIFY:          "nojustify",
	NORMALIZE:          "normalize",
	NOTRANSLATE:        "notranslate",
	NSLIMIT:            "nslimit",
	NSLIMIT1:           "nslimit1",
	ORDERING:           "ordering",
	ORIENTATION:        "orientation",
	OUTPUTORDER:        "outputorder",
	OVERLAP:            "overlap",
	OVERLAP_SCALING:    "overlap_scaling",
	OVERLAP_SHRINK:     "overlap_shrink",
	PACK:               "pack",
	PACKMODE:           "packmode",
	PAD:                "pad",
	PAGE:               "page",
	PAGEDIR:            "pagedir",
	PENCOLOR:           "pencolor",
	PENWIDTH:           "penwidth",
	PERIPHERIES:        "peripheries",
	PIN:                "pin",
	POS:                "pos",
	QUADTREE:           "quadtree",
	QUANTUM:            "quantum",
	RANK:               "rank",
	RANKDIR:            "rankdir",
	RANKSEP:            "ranksep",
	RATIO:              "ratio",
	RECTS:              "rects",
	REGULAR:            "regular",
	REMINCROSS:         "remincross",
	REPULSIVEFORCE:     "repulsiveforce",
	RESOLUTION:         "resolution",
	ROOT:               "root",
	ROTATE:             "rotate",
	ROTATION:           "rotation",
	SAMEHEAD:           "samehead",
	SAMETAIL:           "sametail",
	SAMPLEPOINTS:       "samplepoints",
	SCALE:              "scale",
	SEARCHSIZE:         "searchsize",
	SEP:                "sep",
	SHAPE:              "shape",
	SHAPEFILE:          "shapefile",
	SHOWBOXES:          "showboxes",
	SIDES:              "sides",
	SIZE:               "size",
	SKEW:               "skew",
	SMOOTHING:          "smoothing",
	SORTV:              "sortv",
	SPLINES:            "splines",
	START:              "start",
	STYLE:              "style",
	STYLESHEET:         "stylesheet",
	TAILURL:            "tailURL",
	TAIL_LP:            "tail_lp",
	TAILCLIP:           "tailclip",
	TAILHREF:           "tailhref",
	TAILLABEL:          "taillabel",
	TAILPORT:           "tailport",
	TAILTARGET:         "tailtarget",
	TAILTOOLTIP:        "tailtooltip",
	TARGET:             "target",
	TOOLTIP:            "tooltip",
	TRUECOLOR:          "truecolor",
	VERTICES:           "vertices",
	VIEWPORT:           "viewport",
	VORO_MARGIN:        "voro_margin",
	WEIGHT:             "weight",
	WIDTH:              "width",
	XDOTVERSION:        "xdotversion",
	XLABEL:             "xlabel",
	XLP:                "xlp",
	Z:                  "z",
}

func (a Attribute) String() string {
	return attributeString[a]
}
