name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        path: src/github.com/awalterschulze/gographviz

    - name: Install dependencies
      run: make dependencies

    - name: Run regenerate
      run: make regenerate

    - name: Run build
      run: make build

    - name: Run checkers
      run: make checkers

    - name: Run testing
      run: make test
