name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src/github.com/awalterschulze/gographviz/v2

    steps:
    - name: Set GOPATH
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)/gographviz"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/gographviz/bin"
      shell: bash

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14'

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: src/github.com/awalterschulze/gographviz/v2

    - name: Install dependencies
      run: make dependencies
      working-directory: ${{env.working-directory}}

    - name: Run regenerate
      run: make regenerate
      working-directory: ${{env.working-directory}}

    - name: Run build
      run: make build
      working-directory: ${{env.working-directory}}

    - name: Run checkers
      run: make checkers
      working-directory: ${{env.working-directory}}

    - name: Run testing
      run: make test
      working-directory: ${{env.working-directory}}
