name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Fetch dependencies
      run: go mod download -x

    - name: Install tools
      run: go install -x github.com/kisielk/errcheck golang.org/x/lint/golint github.com/goccmack/gocc

    - name: gocc
      run: gocc -zip -o ./internal/ dot.bnf

    - name: build
      run: go build .

    - name: err check
      run: errcheck -ignore 'fmt:[FS]?[Pp]rint*' ./...

    - name: fmt
      run: gofmt -l -s -w .

    - name: lint
      run: golint -set_exit_status

    - name: diff
      run: git diff --exit-code

    - name: test
      run: go test ./...
